INSERT INTO public.incidencias (idaula,estado,autor,fecha,descripcion,solucion,prioridad,clase,idequipo) VALUES
	 (1,'resuelta','Manu','2025-05-08','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','3','hardware',21),
	 (2,'creada','Javier','2025-05-13','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','2','hardware',18),
	 (6,'resuelta','Pedro','2025-05-06','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','3','software',13),
	 (6,'procesada','Guille','2025-05-06','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','1','software',22),
	 (5,'procesada','Alfredo','2025-05-13','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','2','hardware',13),
	 (6,'resuelta','Aurora','2025-05-06','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','2','software',21),
	 (5,'resuelta','Jose Cavas','2025-05-13','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','2','hardware',13),
	 (5,'procesada','Paco','2025-05-08','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','2','hardware',13),
	 (3,'resuelta','Aurora','2025-05-07','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','1','software',13),
	 (1,'resuelta','Aurora','2025-05-04','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','2','software',21);
INSERT INTO public.incidencias (idaula,estado,autor,fecha,descripcion,solucion,prioridad,clase,idequipo) VALUES
	 (2,'creada','Antonio','2025-05-07','','','1','hardware',13),
	 (6,'procesada','Alejandro','2025-05-08','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','1','software',21),
	 (6,'procesada','Andrés','2025-05-08','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','3','hardware',22),
	 (5,'resuelta','Pedro','2025-05-08','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','2','software',22),
	 (6,'resuelta','Aurora','2025-05-06','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','3','hardware',22),
	 (1,'resuelta','Alejandro','2025-05-12','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','3','software',24),
	 (4,'resuelta','Bartolo','2025-05-19','Uennenxksw','Jdbfjjekwjjdbzbwbbw','3','hardware',14),
	 (5,'procesada','AURORA','2025-05-19','','','2','hardware',13),
	 (4,'resuelta','Iván','2025-05-20','','','3','hardware',14),
	 (1,'procesada','dujdjd','2025-05-20','','','1','software',24);
INSERT INTO public.incidencias (idaula,estado,autor,fecha,descripcion,solucion,prioridad,clase,idequipo) VALUES
	 (8,'resuelta','hhhhh','2025-05-20','','','2','software',25),
	 (1,'resuelta','Dariana','2025-05-15','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','1','software',6),
	 (6,'resuelta','Pepito','2025-05-15','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','3','software',28),
	 (6,'resuelta','Aurora','2025-05-06','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','1','hardware',21),
	 (1,'creada','Pacopico','2025-05-14','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','1','software',23),
	 (1,'procesada','ssss','2025-05-15','er','jhh','2','software',24),
	 (4,'resuelta','yo','2025-05-17','k','j','3','hardware',14),
	 (1,'resuelta','Aurorita','2025-05-15','Descripción muy larga. Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.Descripción muy larga.','Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.Solución muy larga.','1','software',6),
	 (5,'resuelta','yo','2025-05-17','v','j','1','software',13),
	 (1,'procesada','yo','2025-05-19','S','aa','1','software',24);
